import { Item, User } from "../types";

export const CATEGORIES = [
  "Electronics",
  "Bags & Backpacks",
  "Keys",
  "Wallets & Purses",
  "Watches & Jewelry",
  "Documents & IDs",
  "Accessories",
  "Clothing",
  "Other",
];

export const LOCATIONS = [
  "Campus Quad",
  "Central Library",
  "Science Hall",
  "Downtown Station",
  "City Park",
  "North Cafeteria",
  "Sports Complex",
  "Main Street Bus Stop",
];

export const DEMO_USERS: Record<string, User> = {
  alex: {
    id: "u1",
    name: "Alex Rivera",
    avatarUrl: undefined, // Will generate initials placeholder in UI
    memberSince: "May 2026",
  },
  sarah: {
    id: "u2",
    name: "Sarah Chen",
    avatarUrl: undefined,
    memberSince: "February 2026",
  },
  marcus: {
    id: "u3",
    name: "Marcus Johnson",
    avatarUrl: undefined,
    memberSince: "January 2026",
  },
  elena: {
    id: "u4",
    name: "Elena Rostova",
    avatarUrl: undefined,
    memberSince: "June 2026",
  },
};

export const DEMO_ITEMS: Item[] = [
  // Lost Items
  {
    id: "lost-1",
    title: "Black AirPods Pro",
    description: "Lost my AirPods Pro in a black silicone case. The case has a small scratch on the front LED indicator. Left them on a desk on the 2nd floor study area.",
    category: "Electronics",
    status: "lost",
    location: "Central Library",
    date: "2026-08-10",
    color: "Black",
    brand: "Apple",
    reporter: DEMO_USERS.alex,
    isSaved: false,
  },
  {
    id: "lost-2",
    title: "Blue Fjallraven Backpack",
    description: "Navy blue Kanken backpack containing class notebooks, a purple pencil case, and a textbook. Left near the entrance benches.",
    category: "Bags & Backpacks",
    status: "lost",
    location: "Science Hall",
    date: "2026-08-08",
    color: "Blue",
    brand: "Fjallraven",
    reporter: DEMO_USERS.sarah,
    isSaved: true,
  },
  {
    id: "lost-3",
    title: "University Student ID Card",
    description: "Student ID card with name Sarah Chen and photo. Essential for my exams this week. Please let me know if found!",
    category: "Documents & IDs",
    status: "lost",
    location: "Campus Quad",
    date: "2026-08-10",
    color: "White/Blue",
    brand: "University",
    reporter: DEMO_USERS.sarah,
    isSaved: false,
  },
  {
    id: "lost-4",
    title: "Silver Seiko Chronograph Watch",
    description: "Silver stainless steel men's watch with a dark blue dial. It has some minor wear on the metal clasp. Sentimental value.",
    category: "Watches & Jewelry",
    status: "lost",
    location: "Sports Complex",
    date: "2026-08-07",
    color: "Silver",
    brand: "Seiko",
    reporter: DEMO_USERS.marcus,
    isSaved: false,
  },
  {
    id: "lost-5",
    title: "MacBook USB-C Power Charger",
    description: "Apple 96W USB-C power brick with a 2-meter white charging cable. Left plugged into the wall outlet near the window tables.",
    category: "Electronics",
    status: "lost",
    location: "North Cafeteria",
    date: "2026-08-09",
    color: "White",
    brand: "Apple",
    reporter: DEMO_USERS.elena,
    isSaved: false,
  },

  // Found Items
  {
    id: "found-1",
    title: "Black Leather Bi-fold Wallet",
    description: "Found a black leather wallet on the bench near Platform 2. Contains some local store loyalty cards, but no driver's license or ID. Handed to station office, but posting here to find owner.",
    category: "Wallets & Purses",
    status: "found",
    location: "Downtown Station",
    date: "2026-08-10",
    color: "Black",
    brand: "Fossil",
    reporter: DEMO_USERS.marcus,
    isSaved: false,
  },
  {
    id: "found-2",
    title: "Brass Keychain with 3 Keys",
    description: "Found keys on a metal rings including a brass house key, a small silver padlock key, and a black plastic car key fob (looks like Honda). Found on the grass.",
    category: "Keys",
    status: "found",
    location: "Campus Quad",
    date: "2026-08-09",
    color: "Gold/Brass",
    brand: "Honda",
    reporter: DEMO_USERS.alex,
    isSaved: false,
  },
  {
    id: "found-3",
    title: "Hydro Flask Water Bottle",
    description: "Olive green 32oz Hydro Flask with a flex cap and rubber boot. Found near the children's playground slide area. It has a few sticker residues on it.",
    category: "Accessories",
    status: "found",
    location: "City Park",
    date: "2026-08-10",
    color: "Green",
    brand: "Hydro Flask",
    reporter: DEMO_USERS.elena,
    isSaved: false,
  },
  {
    id: "found-4",
    title: "Anker Wireless Earbuds",
    description: "Found a pair of black Soundcore wireless earbuds inside their charging case. Found sitting on the window sill in Room 302.",
    category: "Electronics",
    status: "found",
    location: "Science Hall",
    date: "2026-08-09",
    color: "Black",
    brand: "Anker",
    reporter: DEMO_USERS.sarah,
    isSaved: false,
  },
  {
    id: "found-5",
    title: "Brown Leather Dotted Notebook",
    description: "Found a pocket-sized Moleskine notebook. Leather cover is dark brown. The first few pages have hand-drawn sketches. Left at the lobby reception desk.",
    category: "Other",
    status: "found",
    location: "Central Library",
    date: "2026-08-08",
    color: "Brown",
    brand: "Moleskine",
    reporter: DEMO_USERS.alex,
    isSaved: false,
  },
];

export const DEMO_STATS = {
  reported: 10420,
  matches: 7650,
  reunited: 4215,
  members: 8190,
};

export const DEMO_MATCH = {
  lostItem: DEMO_ITEMS[0], // Black AirPods Pro
  foundItem: {
    id: "match-found-1",
    title: "Black wireless earbuds",
    description: "Found black bluetooth earbuds in a black charging case. Located on the 2nd floor library area.",
    category: "Electronics",
    status: "found" as const,
    location: "Central Library",
    date: "2026-08-10",
    color: "Black",
    brand: "Apple",
    reporter: DEMO_USERS.marcus,
  },
  matchScore: 87,
  factors: [
    { name: "Category Match", score: 25, matched: true, value: "Electronics" },
    { name: "Location Match", score: 25, matched: true, value: "Central Library" },
    { name: "Date Range Match", score: 20, matched: true, value: "Same Day" },
    { name: "Color Match", score: 12, matched: true, value: "Black" },
    { name: "Description Analysis", score: 5, matched: false, value: "High Similarity" },
  ],
};
